version: '3.8'

services:
  # Main application service
  topbloc-api:
    build: .
    container_name: topbloc-backend-challenge
    ports:
      - "4567:4567"
    environment:
      - JAVA_OPTS=-Xmx512m
    volumes:
      # Mount the database file to persist data
      - ./challenge.db:/app/challenge.db
      # Mount source code for development (optional)
      - ./src:/app/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4567/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a lightweight database browser for SQLite
  sqlite-web:
    image: coleifer/sqlite-web
    container_name: topbloc-db-browser
    ports:
      - "8080:8080"
    volumes:
      - ./challenge.db:/data/challenge.db
    command: ["sqlite_web", "/data/challenge.db", "--host", "0.0.0.0", "--port", "8080"]
    depends_on:
      - topbloc-api
    restart: unless-stopped

networks:
  default:
    name: topbloc-network
